# IP address to listen on, leave empty to listen on anything
address = ""
port = 80
# Hex encode the users IP and use it as the ident
hexIP = false
verify_certificates = true

# Defaults for the client connect form
[defaults]
name = "Freenode"
host = "chat.freenode.net"
port = 6697
channels = [
  "#dispatch",
  "#go-nuts"
]
password = ""
ssl = true
# Only allow a nick to be filled in
readonly = false
# Show server and channel info when readonly is enabled
show_details = false

[https]
enabled = true
port = 443
# Path to your cert and private key if you are not using
# the Let's Encrypt integration
cert = ""
key = ""

[letsencrypt]
# Your domain or subdomain, if not set a certificate will be
# fetched for whatever domain dispatch gets accessed through
domain = ""
# An email address lets you recover your accounts private key
email = ""

# Not implemented
[auth]
# Allow usage without being logged in, all channels and settings get
# transferred when logging in or registering
anonymous = true
# Enable username/password login
login = true
# Enable username/password registration
registration = true

[auth.github]
key = ""
secret = ""

[auth.facebook]
key = ""
secret = ""

[auth.google]
key = ""
secret = ""

[auth.twitter]
key = ""
secret = ""

# Strict-Transport-Security
[https.hsts]
enabled = false
max_age = 31536000
include_subdomains = false
preload = false
